### ISSUE TITLE
transform file in the classpath

### ISSUE THREAD

**Issue by rbrasga** [ChrisHarrold/SpringDemoCE2015#4]
You need to make sure the transform file is in the classpath. Could you add a note about that?

Here's a good note:
# xd:> stream create --name groovytransformtest2 --definition "http --port=9004 | transform --script=custom-transform.groovy --propertiesLocation=custom-transform.properties | log" --deploy
## By default, Spring XD will search the classpath for custom-transform.groovy and custom-transform.properties. You can place the script in ${xd.home}/modules/processor/scripts and the properties file in ${xd.home}/config to make them available on the classpath. Alternatively, you can prefix the script and properties-location values with file: to load from the file system.

Source: http://docs.spring.io/spring-xd/docs/current-SNAPSHOT/reference/html/#transform

**Comment by ChrisHarrold** [comment]
Yeah - that was dumb of me - I forgot to say that if you do not set the classpath variable (as per the documentation snipit you posted) you can just put the transform script into the proper directory and that will work too. (and in a couple of ways is easier since you do not have to muck with the XML for defining the processor config - at least for the demo, I would probably take that approach in the "production" product). 

Anyway - updated the readme file to include this info, and thanks for that catch!
